### ISSUE TITLE
Perfil de usuario

### ISSUE THREAD

**Issue by maximilianogarcia6** [maximilianogarcia6/ObligatorioIS2#2]
Permitir almacenar un perfil de usuario (Nombre, Foto y partidos jugados y ganados). Esta información debe persistir.

- Crear una nueva branch en GIT
- Diseñar caso de prueba
- Programar la funcionalidad para que ejecute el caso de prueba
- Refactoring de código
- Revisar prueba
- Una vez obtenida la funcionalidad, hacer merge a la linea base de GIT

**Comment by feloc50** [comment]
Se creo la branch User para desarrollar la funcionalidad. Se diseño la funcionalidad guiada por TDD, realizando la prueba ROJA y VERDE. Se completo el proceso con la funcionalidad creada.

**Comment by maximilianogarcia6** [comment]
Estado: Asignado 
Categoría: Mejora
Asignado a: Felipe Cordoves
Prioridad: Alta
Grado de severidad: N/A
