### ISSUE TITLE
Color de ficha y foto

### ISSUE THREAD

**Issue by maximilianogarcia6** [maximilianogarcia6/ObligatorioIS2#3]
Permitir a los usuarios elegir el color de la ficha y subir una foto.

- Crear una nueva branch en GIT
- Diseñar caso de prueba
- Programar la funcionalidad para que ejecute el caso de prueba
- Refactoring de código
- Revisar prueba
- Una vez obtenida la funcionalidad, hacer merge a la linea base de GIT

**Comment by feloc50** [comment]
Funcionalidad Creada y Probada con éxito. No pareció necesario crear prueba unitaria para esta funcionalidad que involucraba mas temas de UI
